s(sick,[gender = 1, age = 1, hypertension = 60-70, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).
s(sick,[gender = 1, age = 1, hypertension = 60-70, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).
s(healthy,[gender = 1, age = 0, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 4, avg_glucose_level = 1, bmi = 125, smoking_status = 25-30]).
s(healthy,[gender = 1, age = 0, hypertension = 80, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 25-30]).
s(sick,[gender = 0, age = 0, hypertension = 30-40, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 1, age = 0, hypertension = 80, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 3, avg_glucose_level = 0, bmi = 0-110, smoking_status = 18-25]).
s(healthy,[gender = 0, age = 0, hypertension = 40-50, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 0, age = 0, hypertension = 30-40, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 0, age = 0, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 0, residence_type = 2, avg_glucose_level = 1, bmi = 125, smoking_status = 18-25]).
s(healthy,[gender = 1, age = 1, hypertension = 80, heart_disease = 0, ever_married = 1, work_type = 1, residence_type = 4, avg_glucose_level = 0, bmi = 0-110, smoking_status = 18-25]).
s(healthy,[gender = 1, age = 0, hypertension = 60-70, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 125, smoking_status = 30]).
s(healthy,[gender = 0, age = 0, hypertension = 30-40, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 30]).
s(sick,[gender = 1, age = 1, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 18-25]).
s(healthy,[gender = 0, age = 0, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 30]).
s(sick,[gender = 1, age = 0, hypertension = 60-70, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 4, avg_glucose_level = 0, bmi = 110-119, smoking_status = 30]).
s(healthy,[gender = 0, age = 1, hypertension = 60-70, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 3, avg_glucose_level = 1, bmi = 125, smoking_status = 25-30]).
s(healthy,[gender = 0, age = 0, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 0, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 25-30]).
s(sick,[gender = 1, age = 1, hypertension = 70-80, heart_disease = 0, ever_married = 1, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 18-25]).
s(healthy,[gender = 1, age = 0, hypertension = 30-40, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 25-30]).
s(healthy,[gender = 0, age = 0, hypertension = 50-60, heart_disease = 0, ever_married = 0, work_type = 0, residence_type = 3, avg_glucose_level = 0, bmi = 0-110, smoking_status = 18-25]).
s(sick,[gender = 1, age = 0, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 110-119, smoking_status = 18-25]).
s(healthy,[gender = 1, age = 1, hypertension = 70-80, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 125, smoking_status = 25-30]).
s(sick,[gender = 0, age = 0, hypertension = 50-60, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 4, avg_glucose_level = 1, bmi = 110-119, smoking_status = 25-30]).
s(healthy,[gender = 0, age = 1, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 0, residence_type = 1, avg_glucose_level = 1, bmi = 0-110, smoking_status = 25-30]).
s(healthy,[gender = 0, age = 1, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 0, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 1, age = 1, hypertension = 60-70, heart_disease = 1, ever_married = 0, work_type = 0, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).
s(sick,[gender = 0, age = 0, hypertension = 70-80, heart_disease = 1, ever_married = 1, work_type = 1, residence_type = 3, avg_glucose_level = 1, bmi = 125, smoking_status = 25-30]).
s(healthy,[gender = 1, age = 0, hypertension = 50-60, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 4, avg_glucose_level = 1, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 1, age = 1, hypertension = 80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 3, avg_glucose_level = 0, bmi = 0-110, smoking_status = 30]).
s(sick,[gender = 0, age = 0, hypertension = 40-50, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 3, avg_glucose_level = 0, bmi = 0-110, smoking_status = 18-25]).
s(healthy,[gender = 1, age = 0, hypertension = 70-80, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 3, avg_glucose_level = 0, bmi = 125, smoking_status = 18-25]).
s(healthy,[gender = 1, age = 1, hypertension = 60-70, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 125, smoking_status = 30]).
s(sick,[gender = 1, age = 1, hypertension = 60-70, heart_disease = 0, ever_married = 1, work_type = 1, residence_type = 3, avg_glucose_level = 1, bmi = 110-119, smoking_status = 30]).
s(sick,[gender = 1, age = 1, hypertension = 40-50, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 0, age = 0, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 0, residence_type = 1, avg_glucose_level = 1, bmi = 0-110, smoking_status = 18-25]).
s(healthy,[gender = 1, age = 1, hypertension = 50-60, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 25-30]).
s(sick,[gender = 0, age = 0, hypertension = 60-70, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 1, age = 1, hypertension = 70-80, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).
s(healthy,[gender = 1, age = 1, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 3, avg_glucose_level = 0, bmi = 0-110, smoking_status = 18-25]).
s(sick,[gender = 1, age = 0, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).
s(healthy,[gender = 1, age = 0, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 3, avg_glucose_level = 0, bmi = 0-110, smoking_status = 30]).
s(sick,[gender = 1, age = 1, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 25-30]).
s(healthy,[gender = 1, age = 0, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 0, age = 0, hypertension = 60-70, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 25-30]).
s(sick,[gender = 1, age = 1, hypertension = 80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 4, avg_glucose_level = 1, bmi = 125, smoking_status = 25-30]).
s(sick,[gender = 1, age = 1, hypertension = 50-60, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 4, avg_glucose_level = 1, bmi = 0-110, smoking_status = 25-30]).
s(sick,[gender = 1, age = 1, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 3, avg_glucose_level = 1, bmi = 125, smoking_status = 18-25]).
s(healthy,[gender = 0, age = 1, hypertension = 30-40, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 0, age = 0, hypertension = 80, heart_disease = 0, ever_married = 1, work_type = 0, residence_type = 2, avg_glucose_level = 1, bmi = 125, smoking_status = 18-25]).
s(sick,[gender = 1, age = 0, hypertension = 50-60, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 125, smoking_status = 30]).
s(healthy,[gender = 0, age = 1, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 25-30]).
s(healthy,[gender = 0, age = 0, hypertension = 40-50, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 3, avg_glucose_level = 0, bmi = 110-119, smoking_status = 30]).
s(sick,[gender = 1, age = 0, hypertension = 40-50, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 0, age = 0, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 0, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 25-30]).
s(sick,[gender = 0, age = 0, hypertension = 40-50, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).
s(healthy,[gender = 0, age = 0, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 0, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 1, age = 0, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 1, bmi = 0-110, smoking_status = 18-25]).
s(sick,[gender = 0, age = 1, hypertension = 50-60, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 110-119, smoking_status = 25-30]).
s(healthy,[gender = 0, age = 1, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 0, residence_type = 1, avg_glucose_level = 1, bmi = 119-125, smoking_status = 0-18]).
s(healthy,[gender = 0, age = 0, hypertension = 50-60, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 18-25]).
s(sick,[gender = 1, age = 1, hypertension = 60-70, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 18-25]).
s(healthy,[gender = 1, age = 0, hypertension = 50-60, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 4, avg_glucose_level = 1, bmi = 125, smoking_status = 25-30]).
s(healthy,[gender = 0, age = 0, hypertension = 50-60, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).
s(healthy,[gender = 1, age = 0, hypertension = 70-80, heart_disease = 0, ever_married = 1, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).
s(sick,[gender = 0, age = 0, hypertension = 30-40, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 25-30]).
s(healthy,[gender = 0, age = 0, hypertension = 0-30, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 0-110, smoking_status = 30]).
s(healthy,[gender = 0, age = 1, hypertension = 30-40, heart_disease = 0, ever_married = 0, work_type = 0, residence_type = 3, avg_glucose_level = 1, bmi = 0-110, smoking_status = 30]).
s(sick,[gender = 0, age = 0, hypertension = 70-80, heart_disease = 0, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).
s(healthy,[gender = 0, age = 0, hypertension = 70-80, heart_disease = 0, ever_married = 1, work_type = 1, residence_type = 3, avg_glucose_level = 0, bmi = 125, smoking_status = 25-30]).
s(healthy,[gender = 0, age = 1, hypertension = 50-60, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).
s(healthy,[gender = 0, age = 0, hypertension = 60-70, heart_disease = 1, ever_married = 0, work_type = 1, residence_type = 2, avg_glucose_level = 0, bmi = 125, smoking_status = 30]).