s(healthy,[gender = 0, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '70-80', hypertension = 1, heart_disease = 0, ever_married = 0, work_type = 'Govt job', residence_type = 'City', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 0, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'City', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Smokes']).
s(healthy,[gender = 0, age = '70-80', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Formerly smoked']).
s(sick,[gender = 0, age = '40-50', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Formerly smoked']).
s(sick,[gender = 0, age = '80+', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(healthy,[gender = 1, age = '70-80', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '126+', bmi = '26-30', smoking_status = 'Formerly smoked']).
s(sick,[gender = 0, age = '70-80', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 1, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '111-119', bmi = '26-30', smoking_status = 'Formerly smoked']).
s(sick,[gender = 1, age = '70-80', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '50-60', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'City', avg_glucose_level = '126+', bmi = '26-30', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '50-60', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'City', avg_glucose_level = '126+', bmi = '19-25', smoking_status = 'Smokes']).
s(healthy,[gender = 0, age = '30-40', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '80+', hypertension = 0, heart_disease = 1, ever_married = 0, work_type = 'Private', residence_type = 'City', avg_glucose_level = '126+', bmi = '19-25', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '70-80', hypertension = 1, heart_disease = 1, ever_married = 0, work_type = 'Govt job', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '40-50', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Smokes']).
s(healthy,[gender = 0, age = '40-50', hypertension = 1, heart_disease = 0, ever_married = 0, work_type = 'Self employed', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '26-30', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '70-80', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '40-50', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Govt job', residence_type = 'City', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '70-80', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Formerly smoked']).
s(sick,[gender = 0, age = '80+', hypertension = 1, heart_disease = 1, ever_married = 1, work_type = 'Govt job', residence_type = 'City', avg_glucose_level = '126+', bmi = '26-30', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 0, age = '30-40', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '126+', bmi = '26-30', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '70-80', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'City', avg_glucose_level = '126+', bmi = '26-30', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 1, age = '70-80', hypertension = 0, heart_disease = 1, ever_married = 1, work_type = 'Self employed', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Smokes']).
s(healthy,[gender = 0, age = '40-50', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Smokes']).
s(sick,[gender = 1, age = '70-80', hypertension = 1, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'City', avg_glucose_level = '111-119', bmi = '19-25', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Never smoked']).
s(healthy,[gender = 1, age = '40-50', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Formerly smoked']).
s(sick,[gender = 0, age = '70-80', hypertension = 0, heart_disease = 1, ever_married = 1, work_type = 'Self employed', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 0, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '70-80', hypertension = 0, heart_disease = 1, ever_married = 0, work_type = 'Private', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Smokes']).
s(healthy,[gender = 0, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(healthy,[gender = 1, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '60-70', hypertension = 1, heart_disease = 1, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Smokes']).
s(healthy,[gender = 1, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'City', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'City', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Formerly smoked']).
s(sick,[gender = 1, age = '60-70', hypertension = 0, heart_disease = 1, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '111-119', bmi = '26-30', smoking_status = 'Smokes']).
s(healthy,[gender = 0, age = '50-60', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Smokes']).
s(sick,[gender = 0, age = '70-80', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 1, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '50-60', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '60-70', hypertension = 0, heart_disease = 1, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Formerly smoked']).
s(sick,[gender = 0, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '80+', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Formerly smoked']).
s(sick,[gender = 1, age = '50-60', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Formerly smoked']).
s(sick,[gender = 0, age = '50-60', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 0, age = '40-50', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Smokes']).
s(healthy,[gender = 1, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'City', avg_glucose_level = '120-125', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 1, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 1, age = '30-40', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'City', avg_glucose_level = '126+', bmi = '26-30', smoking_status = 'Smokes']).
s(sick,[gender = 1, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'Rural', avg_glucose_level = '111-119', bmi = '31+', smoking_status = 'Smokes']).
s(healthy,[gender = 0, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 1, age = '50-60', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '70-80', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Self employed', residence_type = 'City', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '70-80', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Smokes']).
s(sick,[gender = 1, age = '70-80', hypertension = 0, heart_disease = 1, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '19-25', smoking_status = 'Formerly smoked']).
s(sick,[gender = 0, age = '50-60', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(healthy,[gender = 1, age = '50-60', hypertension = 0, heart_disease = 1, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 0, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Smokes']).
s(healthy,[gender = 0, age = '40-50', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '19-25', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '70-80', hypertension = 0, heart_disease = 1, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '40-50', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(healthy,[gender = 1, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 0, age = '30-40', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '70-80', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Formerly smoked']).
s(sick,[gender = 1, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '26-30', smoking_status = 'Never smoked']).
s(sick,[gender = 0, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 0, age = '30-40', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Smokes']).
s(sick,[gender = 1, age = '60-70', hypertension = 0, heart_disease = 1, ever_married = 1, work_type = 'Self employed', residence_type = 'City', avg_glucose_level = '126+', bmi = '26-30', smoking_status = 'Smokes']).
s(sick,[gender = 1, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 0, age = '30-40', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Smokes']).
s(sick,[gender = 0, age = '70-80', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '111-119', bmi = '19-25', smoking_status = 'Formerly smoked']).
s(sick,[gender = 0, age = '60-70', hypertension = 0, heart_disease = 1, ever_married = 1, work_type = 'Govt job', residence_type = 'Rural', avg_glucose_level = '120-125', bmi = '31+', smoking_status = 'Smokes']).
s(sick,[gender = 0, age = '50-60', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '60-70', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '70-80', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '70-80', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Smokes']).
s(healthy,[gender = 1, age = '50-60', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '70-80', hypertension = 1, heart_disease = 1, ever_married = 1, work_type = 'Private', residence_type = 'City', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Formerly smoked']).
s(healthy,[gender = 0, age = '60-70', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 1, age = '50-60', hypertension = 1, heart_disease = 1, ever_married = 1, work_type = 'Govt job', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '0-30', hypertension = 0, heart_disease = 0, ever_married = 0, work_type = 'Children', residence_type = 'City', avg_glucose_level = '0-110', bmi = '19-25', smoking_status = 'Never smoked']).
s(healthy,[gender = 0, age = '40-50', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Smokes']).
s(healthy,[gender = 1, age = '50-60', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Govt job', residence_type = 'Rural', avg_glucose_level = '0-110', bmi = '26-30', smoking_status = 'Smokes']).
s(healthy,[gender = 0, age = '40-50', hypertension = 0, heart_disease = 0, ever_married = 1, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Formerly smoked']).
s(sick,[gender = 0, age = '60-70', hypertension = 1, heart_disease = 1, ever_married = 0, work_type = 'Self employed', residence_type = 'City', avg_glucose_level = '0-110', bmi = '31+', smoking_status = 'Never smoked']).
s(sick,[gender = 1, age = '70-80', hypertension = 1, heart_disease = 0, ever_married = 1, work_type = 'Self employed', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '26-30', smoking_status = 'Formerly smoked']).
s(sick,[gender = 1, age = '60-70', hypertension = 1, heart_disease = 0, ever_married = 0, work_type = 'Private', residence_type = 'Rural', avg_glucose_level = '126+', bmi = '31+', smoking_status = 'Never smoked']).
